export const workoutMethods = [
  {
    "id": "interval_set_calculator",
    "category": "workout",
    "name": "Interval Set Calculator",
    "requiredInputs": ["reps", "repDistance", "pace", "rest"],
    "optionalInputs": ["warmup", "cooldown", "rpe"],
    "formulaDisplay": "Rep Time = Distance × Pace; Total Time = Work Time + Rest Time + Warmup + Cooldown",
    "precision": "mathematical",
    "limitations": ["Mathematical projection only. Does not factor in fatigue profiles, terrain variety, or cardiovascular drift."],
    "confidenceLabel": "mathematical calculation",
    "implementationStatus": "implemented"
  },
  {
    "id": "total_work_distance",
    "category": "workout",
    "name": "Total Work Distance Calculation",
    "requiredInputs": ["reps", "repDistanceMeters"],
    "formulaDisplay": "Total Distance = Reps × Rep Distance",
    "precision": "mathematical",
    "limitations": ["Only measures high intensity distance, excludes warm-up and cool-down."],
    "confidenceLabel": "exact mathematical product",
    "implementationStatus": "implemented"
  },
  {
    "id": "total_work_time",
    "category": "workout",
    "name": "Total Work Time Calculation",
    "requiredInputs": ["reps", "repTimeSeconds"],
    "formulaDisplay": "Total Work Time = Reps × Rep Time",
    "precision": "mathematical",
    "limitations": ["Only tracks actual intense repetition time, ignoring rest intervals and transitions."],
    "confidenceLabel": "exact mathematical product",
    "implementationStatus": "implemented"
  },
  {
    "id": "total_rest_time",
    "category": "workout",
    "name": "Total Rest Time Calculation",
    "requiredInputs": ["reps", "restSeconds", "restPolicy"],
    "formulaDisplay": "between reps: rest × (reps - 1); after every rep: rest × reps",
    "precision": "mathematical",
    "limitations": ["Assumes player stays stationary or executes perfect recovery jog duration without delay."],
    "confidenceLabel": "exact deterministic model",
    "implementationStatus": "implemented"
  },
  {
    "id": "session_duration",
    "category": "workout",
    "name": "Session Duration Calculation",
    "requiredInputs": ["warmupSeconds", "workSeconds", "restSeconds", "cooldownSeconds"],
    "formulaDisplay": "Session Duration = Warm-up + Work + Rest + Cooldown",
    "precision": "mathematical",
    "limitations": ["Does not account for non-running drills, dynamic mobility preparation, or static stretching."],
    "confidenceLabel": "exact mathematical sum",
    "implementationStatus": "implemented"
  },
  {
    "id": "work_rest_ratio",
    "category": "workout",
    "name": "Work:Rest Ratio",
    "requiredInputs": ["workSeconds", "restSeconds"],
    "formulaDisplay": "Work:Rest = Work Time / Rest Time",
    "precision": "mathematical",
    "limitations": ["A simplistic density indicator that does not reflect absolute cardiac strain or active recovery intensity."],
    "confidenceLabel": "exact ratio",
    "implementationStatus": "implemented"
  },
  {
    "id": "workout_density",
    "category": "workout",
    "name": "Workout Density",
    "requiredInputs": ["workSeconds", "sessionSeconds"],
    "formulaDisplay": "Density = Work Time / Session Time × 100",
    "precision": "mathematical",
    "limitations": ["Higher density does not always dictate superior fitness stimulus. Undersized rest limits peak power output."],
    "confidenceLabel": "percentage index",
    "implementationStatus": "implemented"
  },
  {
    "id": "hard_easy_distribution",
    "category": "workout",
    "name": "Hard/Easy Distribution",
    "requiredInputs": ["hardSeconds", "easySeconds", "restSeconds"],
    "formulaDisplay": "Each % = Category Time / Total Duration × 100",
    "precision": "mathematical",
    "limitations": ["Reflects static plan rather than real-time heart rate or physiological stress zones."],
    "confidenceLabel": "distribution profile",
    "implementationStatus": "implemented"
  },
  {
    "id": "session_rpe_load",
    "category": "workout",
    "name": "Session RPE Load",
    "requiredInputs": ["durationMinutes", "rpe"],
    "formulaDisplay": "sRPE Load = Duration × RPE",
    "precision": "empirical",
    "limitations": ["RPE is highly subjective and depends on athlete psychology, hydration, environmental heat, and pacing skills."],
    "confidenceLabel": "subjective load index",
    "implementationStatus": "implemented"
  },
  {
    "id": "run_walk_workout",
    "category": "workout",
    "name": "Run-Walk Workout Calculator",
    "requiredInputs": ["runDuration", "walkDuration", "cycles", "runPace", "walkPace"],
    "formulaDisplay": "Total Time = cycles × (runDuration + walkDuration); Blended Pace = Total Time / Total Distance",
    "precision": "mathematical",
    "limitations": ["Assumes instantaneous transitions between running and walking speeds without acceleration phase lag."],
    "confidenceLabel": "blended average pace",
    "implementationStatus": "implemented"
  },
  {
    "id": "fartlek_totals",
    "category": "workout",
    "name": "Fartlek Calculator",
    "requiredInputs": ["hardDuration", "easyDuration", "cycles"],
    "optionalInputs": ["hardPace", "easyPace"],
    "formulaDisplay": "Hard Time = cycles × hardDuration; Easy Time = cycles × easyDuration; Hard % = Hard / Total × 100",
    "precision": "mathematical",
    "limitations": ["Estimates volume bounds. Paces typically drift during unstructured outdoor speed play sessions."],
    "confidenceLabel": "unstructured interval projection",
    "implementationStatus": "implemented"
  },
  {
    "id": "hill_repeat_totals",
    "category": "workout",
    "name": "Hill Repeat Calculator",
    "requiredInputs": ["reps", "climbMetersPerRep", "repDuration", "recoveryDuration"],
    "formulaDisplay": "Total Climb = Reps × Climb per Rep; Work Time = Reps × Rep Duration; Recovery Time = Reps × Recovery Duration",
    "precision": "mathematical",
    "limitations": ["Represents geographic work. Musculoskeletal load is considerably higher on uphill profiles."],
    "confidenceLabel": "gravitational vertical gain metric",
    "implementationStatus": "implemented"
  },
  {
    "id": "tempo_run_calculator",
    "category": "workout",
    "name": "Tempo Run Calculator",
    "requiredInputs": ["blockDuration"],
    "optionalInputs": ["pace"],
    "formulaDisplay": "Work Distance = Duration × Speed",
    "precision": "mathematical",
    "limitations": ["Assumes continuous steady-state effort. Actual lactate clearance capacity fluctuates by session."],
    "confidenceLabel": "steady-state pacing model",
    "implementationStatus": "implemented"
  },
  {
    "id": "threshold_block_calculator",
    "category": "workout",
    "name": "Threshold Block Calculator",
    "requiredInputs": ["blockDuration", "reps", "recoveryDuration"],
    "formulaDisplay": "Threshold Time = blockDuration × reps; Total Rest = recoveryDuration × (reps - 1); Session Time = Threshold + Rest",
    "precision": "mathematical",
    "limitations": ["Assumes steady-state kinetics. Does not account for aerobic oxygen deficit in initial block minutes."],
    "confidenceLabel": "deterministic training volume",
    "implementationStatus": "implemented"
  },
  {
    "id": "cruise_interval_calculator",
    "category": "workout",
    "name": "Cruise Interval Calculator",
    "requiredInputs": ["sessionReps", "repDistance", "targetPace", "restSecs"],
    "formulaDisplay": "Distance = reps × repDistance; Work Time = Distance × Pace; Session Time = Work Time + Rest Time",
    "precision": "mathematical",
    "limitations": ["Pacing must remain highly controlled. Wind or elevation changes can elevate threshold efforts to VO2max strain."],
    "confidenceLabel": "lactate threshold control",
    "implementationStatus": "implemented"
  },
  {
    "id": "progression_run_calculator",
    "category": "workout",
    "name": "Progression Run Calculator",
    "requiredInputs": ["startingPace", "incrementPerKm", "totalDistance"],
    "formulaDisplay": "Average Pace = startingPace - (totalDistance - 1) × (increment / 2); Duration = Distance × Average Pace",
    "precision": "mathematical",
    "limitations": ["Expects linear speed growth which is physically hard to maintain toward terminal kilometers."],
    "confidenceLabel": "linear acceleration estimate",
    "implementationStatus": "implemented"
  },
  {
    "id": "ladder_workout_calculator",
    "category": "workout",
    "name": "Ladder Workout Calculator",
    "requiredInputs": ["distances", "pace", "rest"],
    "formulaDisplay": "Total Dist = Sum(distances); Rep Times = distances × Pace",
    "precision": "mathematical",
    "limitations": ["Rest demands are mathematically fixed but biological recovery needs grow as duration changes."],
    "confidenceLabel": "progressive workload layout",
    "implementationStatus": "implemented"
  },
  {
    "id": "pyramid_workout_calculator",
    "category": "workout",
    "name": "Pyramid Workout Calculator",
    "requiredInputs": ["distances", "pace", "rest"],
    "formulaDisplay": "Total Dist = Sum(distances); Total Time = Total Dist * Pace + Rest",
    "precision": "mathematical",
    "limitations": ["Peak repetitions of pyramid impose asymmetric muscular fatigue compared to initial ascents."],
    "confidenceLabel": "symmetrical workload layout",
    "implementationStatus": "implemented"
  },
  {
    "id": "workout_comparison",
    "category": "workout",
    "name": "Workout Comparison Calculator",
    "requiredInputs": ["workoutASummary", "workoutBSummary"],
    "formulaDisplay": "Delta = Value A - Value B",
    "precision": "mathematical",
    "limitations": ["Compares volume and intensity metrics without modeling mechanical stress, biomechanics, or running shoes."],
    "confidenceLabel": "direct mathematical delta",
    "implementationStatus": "implemented"
  },
  {
    "id": "block_based_builder",
    "category": "workout",
    "name": "Block-Based Workout Builder",
    "requiredInputs": ["blockRows"],
    "formulaDisplay": "Total Time = Sum(Duration × Repeats); Total Distance = Sum(Distance × Repeats)",
    "precision": "mathematical",
    "limitations": ["Requires explicit manual entry for every segment. Total distance relies on standard pace approximations."],
    "confidenceLabel": "custom session aggregate",
    "implementationStatus": "implemented"
  },

  // WORKOUT LIBRARY METHODS
  {
    "id": "static_template_browser",
    "category": "workout_library",
    "name": "Static Template Browser",
    "requiredInputs": [],
    "formulaDisplay": "Database scan",
    "precision": "metadata",
    "limitations": ["Templates represent generic structural designs. They are not personalized training plans or coaches."],
    "confidenceLabel": "static reference library",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_filter_purpose",
    "category": "workout_library",
    "name": "Template Filter by Purpose",
    "requiredInputs": ["purpose"],
    "formulaDisplay": "Filter: purpose match",
    "precision": "metadata",
    "limitations": ["Purpose tags focus on primary energy systems. Secondary conditioning effects are not mapped."],
    "confidenceLabel": "static reference library",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_filter_distance",
    "category": "workout_library",
    "name": "Template Filter by Distance",
    "requiredInputs": ["distanceRange"],
    "formulaDisplay": "Filter: volume match",
    "precision": "metadata",
    "limitations": ["Categorized based on typical targets; actual suitability depends heavily on athlete history."],
    "confidenceLabel": "static reference library",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_filter_duration",
    "category": "workout_library",
    "name": "Template Filter by Duration",
    "requiredInputs": ["durationLimit"],
    "formulaDisplay": "Filter: duration bounds",
    "precision": "metadata",
    "limitations": ["Assumes single speed profile. Real session durations shift under varied environmental conditions."],
    "confidenceLabel": "static reference library",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_filter_surface",
    "category": "workout_library",
    "name": "Template Filter by Surface",
    "requiredInputs": ["surfaceType"],
    "formulaDisplay": "Filter: surface suitability",
    "precision": "metadata",
    "limitations": ["Surface recommendations refer to conventional guidelines (track vs road). Individual foot strikes change demand."],
    "confidenceLabel": "static reference library",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_filter_intensity",
    "category": "workout_library",
    "name": "Template Filter by Intensity",
    "requiredInputs": ["intensityTag"],
    "formulaDisplay": "Filter: target intensity",
    "precision": "metadata",
    "limitations": ["Intensity based on nominal coaching targets. Real fatigue increases perceived metabolic strain."],
    "confidenceLabel": "static reference library",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_to_workout_lab",
    "category": "workout_library",
    "name": "Template to Workout Lab",
    "requiredInputs": ["copiedStructure"],
    "formulaDisplay": "Data transfer transfer",
    "precision": "metadata",
    "limitations": ["Manual input values are required in the Destination Lab. No automatic performance evaluation is stored."],
    "confidenceLabel": "state transfer",
    "implementationStatus": "implemented"
  },
  {
    "id": "template_comparison",
    "category": "workout_library",
    "name": "Workout Template Comparison",
    "requiredInputs": ["templateA", "templateB"],
    "formulaDisplay": "Calculated Volume Difference & Intensity delta",
    "precision": "mathematical",
    "limitations": ["Limited to comparing generic template designs without active athlete profile variables or previous logs."],
    "confidenceLabel": "structural comparison",
    "implementationStatus": "implemented"
  },
  {
    "id": "export_template",
    "category": "workout_library",
    "name": "Export Selected Template",
    "requiredInputs": ["templateId"],
    "formulaDisplay": "Manual clipboard string assembly",
    "precision": "metadata",
    "limitations": ["Exports structural metadata alone. Does not preserve individual execution notes or Garmin formats."],
    "confidenceLabel": "text translation",
    "implementationStatus": "implemented"
  }
];
